AWSTemplateFormatVersion: "2010-09-09"
Description: API Gateway, Stage, Key and Usage Plan
Parameters:
  ParentStack:
    Type: String
    Description: Name of parent stack
    Default: my-parent
  LambdaName:
    Description: Name of lambda to integrate
    Type: String
  LambdaURI:
    Description: URI of lambda to integrate
    Type: String
  Environment:
    Description: dev/data
    Type: String
    AllowedValues: ["dev", "data"]
Resources:
  ApiGateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !Sub "${ParentStack}"
      Description: !Sub "API endpoint for ${ParentStack}"
  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: !Ref LambdaName
  ApiGatewayMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      ApiKeyRequired: true
      AuthorizationType: "NONE"
      HttpMethod: "POST"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri: !Ref LambdaURI
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref ApiGateway

  ApiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
      - "ApiGatewayMethod"
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: ""

  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: !Ref Environment
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref ApiGatewayDeployment
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub "${ParentStack}_apikey"
      Description: "CloudFormation API Key"
      Enabled: true
      GenerateDistinctId: false
  ApiUsagePlan:
    Type: "AWS::ApiGateway::UsagePlan"
    Properties:
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: !Ref ApiGatewayStage
      Description: !Sub "${ParentStack} usage plan"
      UsagePlanName: !Sub "${ParentStack}_usage-plan"
  ApiUsagePlanKey:
    Type: "AWS::ApiGateway::UsagePlanKey"
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan

  APIInvokePermissionIgnition:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref LambdaName
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*"
Outputs:
  RestApiID:
    Description: 'Api Gateway ID'
    Value: !Sub "${ApiGateway}"
  InvokeURL:
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"